### ISSUE TITLE
Field transformation while typing

### ISSUE THREAD

**Issue by Luis-Henriquez-Perez** [minad/tempel#25] opened 2022-01-16 21:14 UTC
Back in the day when I used `yasnippet` I created a really cool `defun` snippet for `emacs-lisp-mode` that automatically capitalized symbols I specified in the function arguments _as I wrote_ the docstring (I recalled I used `replace-regexp-in-string`). I'll see if I can find that snippet (or I'll just write it again--it wasn't complicated). Can `tempel` do this? From scrutinizing the elements I do not believe so, but please correct me if I am wrong.

This can be useful in a variety of cases, a simple case is if you want certain words capitalized like in a docstring. Or perhaps you have a snippet for writing secret messages where you want to use `rot13-region` on all the words you type.

**Comment by minad** [comment] 2022-01-16 21:19
We don't support this right now, but I also doubt that we need it. Currently expressions which are transformed in real time are not marked as fields. We could instead also treat them as fields instead with a default value. It wouldn't be difficult to do this. The downside is that as soon as we mark the auto-updated expressions fields, they also act as tab stops, which is probably not desired.

I have the growing feeling that Tempel is not the right tool for you. The goal I have here is to have something simple, not to support all kinds of edge cases. :shrug:

**Comment by minad** [comment] 2022-01-16 21:22
It could be that I've misunderstood you. Take a look at the rst-mode title and the asciibox examples:

~~~
(asciibox "+-" (make-string (length str) ?-) "-+" n
          "| " (s str)                       " |" n
          "+-" (make-string (length str) ?-) "-+" n)
(title (make-string (length title) ?=) n (p "Title: " title) n (make-string (length title) ?=) n)
~~~

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-16 22:31
> I have the growing feeling that Tempel is not the right tool for you. The goal I have here is to have something simple, not to support all kinds of edge cases.

I don't understand this sentiment. None of the snippets I presented fundamentally differ from the ones you provided in the README. The elisp forms were in mine were just longer, that's it. Nor did I ever suggest that we support `edge cases`; and any changes I recommended (such as #23) were both logical and trivial to implement.

The package that is being revived here, `tempo`, is an old package. Examples of `tempo` snippets online are scarce at best. It is only natural to question and try to improve what this package provided.

I am asking questions that need to be asked and proposing changes that should be considered; and in doing so I am Ifurthering the quality and richness of this package.

> Take a look at the rst-mode title and the asciibox examples. See also the gif where the rst-mode title example is shown.

Ok. This is promising; there is already concept of dynamical updating text. It may be that `s` should also have a `noinsert` argument. In the examples you provided, the text around the inserted text was updated dynamically; not the inserted text itself. If `s` had a `no-insert` argument then we can simulate this functionality such as in the example below.

Consideration should be given as to whether this is the best way to have the actual text itself be updated as it seems a bit round-about. But it may be possible to create a `custom` user element from existing ones for this.

```elisp
(docstring (s docstring <NO-INSERT-ARG-GOES-HERE>) "~~" (upcase (or docstring "")) "~~")
```

> except that the docstring is not marked as field (it is not a "default" in our terminology).

Still, I would like the possibility of a default value with this. Exactly how this should be done needs further consideration.

**Comment by minad** [comment] 2022-01-16 22:58
> I don't understand this sentiment.

First, let me say that I very much appreciate your proposals! However for example the style you write your snippets composed with quasi quoting within the init.el is already special. This deviates from how this package was originally intended to be used. This deviates from how probably most users will use this package, if it will even get adopted by someone. Of course you can do all these things and I intentionally expose the APIs (You can dynamically generate snippets for example and then expand them with `tempel-insert`). Obviously your approach influences your opinion. It is good to have different point of views at the same thing. However if both our perspectives differ too much we won't find a common goal. Does it make sense what I am trying to say?

For now my goal would be to keep this thing as simple as possible and not add language elements. If we can work with this that's great. In the next step we can add more syntax elements, but my personal bias is that the existing syntax elements take us very far. From how I understood you, you said that already the few very first snippets you tried to write were not possible with the existing facilities, while for me it looks as if we can cover a lot of ground with the existing facilities. So far I only played with toy examples and looked into some of the existing snippet collections.

> Ok. This is promising; there is already concept of dynamical updating text. 

Yes.

> In the examples you provided, the text around the inserted text was updated dynamically; not the inserted text itself. 

Okay, you want to transform the input while typing. My first reaction is that this feature is out of scope. Adding such a feature is an entirely new feature which differs from the existing features. I argue that it does not pull its weight. Furthermore such live transformations are very restricted. They only work well if the length of the input is unchanged etc.

> Still, I would like the possibility of a default value with this. 

I must admit, I don't really understand what you want to have. Please present snippets which I can try and then tell me what exactly is missing to make the snippet better. I would appreciate if the snippets you write are written in a form which I can paste into the `templates` file. The form of the templates in the `templates` file is intentionally restricted. This means there are snippets you cannot write. But I consider snippets which do not fit into this framework already as "special" and "unrestricted". So if we want to discuss additional syntax elements it should be possible to discuss this within the framework of the restricted snippets. Furthermore my recommendation is to write as many snippets as possible in the restricted form since this gives us a clearer picture on where the `templates` file is actually too restricted. Maybe restrictions can and should be lifted, maybe not.

**Comment by minad** [comment] 2022-01-16 23:09
> Back in the day when I used yasnippet I created a really cool defun snippet for emacs-lisp-mode that automatically capitalized symbols I specified in the function arguments as I wrote the docstring (I recalled I used replace-regexp-in-string). I'll see if I can find that snippet (or I'll just write it again--it wasn't complicated). Can tempel do this? From scrutinizing the elements I do not believe so, but please correct me if I am wrong.

Ah, I think now I understand what you tried to achieve. I would approach the problem differently. I would implement the docstring as a dynamically updating text where the arguments are transformed to upper case. Example:

~~~ elisp
("(defun " p " (" (s args) ")\n  \"Docstring\n" (string-join (split-string (upcase (or args ""))) "\n") "\"" n> r> ")")
~~~

But I see that this is less valuable than automatically upcasing function arguments when typing the docstring.

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-17 01:14
> However for example the style you write your snippets composed with quasi quoting within the init.el is already special. This deviates from how this package was originally intended to be used.

I find this`"quasi-quote" example you mentioned unusual. Using backquotes the way I did is just a reorganization of elisp code for improved readability. It's still elisp whether its in that form or the way you write it. So to design snippets that can be defined in elisp and then to say that they were only meant to be used with elisp that's structured in a particular way is strange to me.

> However if both our perspectives differ too much we won't find a common goal. Does it make sense what I am trying to say?

I agree with what you say of it being hard to find a common goal with very different perspectives. I just don't think the "quasi-quote" example was the best example for demonstrating this. I don't see how the difference in preference of elisp code structure would prevent us from finding a common goal here.

> In the next step we can add more syntax elements, but my personal bias is that the existing syntax elements take us very far.

I agree with this. All I'm saying is that they might not be perfect. I also do not want to add any superfluous elements.

> From how I understood you, you said that already the few very first snippets you tried to write were not possible with the existing facilities.

This snippet language is powerful. But the template elements are like pieces of a puzzle. Sometimes it is not clear what's possible from looking at the individual elements. It's helpful to see them being used in combination to accomplish tasks. For example, in the id snippet I had been working on I didn't realize I could use a "non-inserting" `p` element to "let-bind" variables.

These kind of snippets which show this unique usage would be a great value to users who will probably end up having the same question. And even if they don't have this question they could benefit from discovering this can be done. This is a big reason I think the wiki is important.

```elisp
(let* ((form `(-let* ((org-refile-use-outline-path t)
			((_ file _ point) (org-refile-get-location "id"))
			(id (with-current-buffer (get-file-buffer file) (org-id-get point))))
		  (list file point id)))
	 (heading `(with-current-buffer (get-file-buffer (cl-first vars))
		     (save-excursion (goto-char (cl-second vars)) (org-get-heading)))))
    `((p ,form vars t) "[[id:" (cl-third vars) "][" (p ,heading) "]"))
```

But to respond to your comment--I do not want to suggest that snippets I want to write are "not possible with existing elements". More often than just clever combination of the existing elements can satisfy my usage question. And in the case that this is not enough probably slight changes to the existing elements--that should probably be done anyway like #23. Instead of scrapping the elements, I am striving to refine them and creating new ones only if it is justified by a valuable feature.

> Adding such a feature is an entirely new feature which differs from the existing features.

There are already examples of dynamically updating text in the readme. They don't seem entirely different to me.

>  They only work well if the length of the input is unchanged etc.

Moreover, the examples in the readme work with changing input length. So do the examples I suggested.

> The form of the templates in the templates file is intentionally restricted. This means there are snippets you cannot write. But I consider snippets which do not fit into this framework already as "special" and "unrestricted".

> So if we want to discuss additional syntax elements it should be possible to discuss this within the framework of the restricted snippets.

I don't understand what you mean by "framework of the restricted snippets". Don't all syntax elements work in both elisp defined snippets or file-syntax defined snippets?

>  Please present snippets which I can try and then tell me what exactly is missing to make the snippet better. I would appreciate if the snippets you write are written in a form which I can paste into the templates file.

That's fair. Will do.

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-17 04:28
So this snippet does _not_ work. I provide it as a demonstration of what should be.

I will explain my analysis.

From studying the template syntax, I realized that it is important to have a means of manipulating inserted text that is not attained via a prompt. `p` expects you to get the text via a prompt. In contrast `s` lets you get the text merely by typing it in--the most basic way.

I propose `s` be given the similar arguments as `p`. Thus the signature for `s` will look like this:

```elisp
(s <DEFAULT> <NAME> <FORM>)
```

<DEFAULT> and <NAME> will be the same as with `p`. Optional <FORM> will be a lisp expression. Specifically,  <FORM>, if specified, should be a lisp expression that returns the transformed text. So if <NAME> is `foo`. Form can be `(upcase foo)`.

```("~~" (s "hi" word (replace-regexp-in-string (rx (or "o" "s" "r" "n")) #'upcase word)) "~~")```.

This (not working) snippet will behave like so.

1. ```~~hi~~``` - just after template expansion
2. ```~~d~~```  - types "d"
3. ```~~dO~~``` - types "o"
4. ```~~dOcStRiNg~~``` - types "cstring"

Things to mention:

- The original behavior of `s` can be achieved with `(s nil NAME)`
- `no-insert` does not make sense with `s` (correct me if I'm wrong)

Finally, I need to keep thinking about the syntax. This proposal right now is more of an idea I need to keep thinking about--and I will as I keep creating more snippets.

**Comment by minad** [comment] 2022-01-17 06:56
The example you gave is not a realistic example. It is a demonstration. If we want to justify if new elements are to be added we have to discuss about realistic snippets. To be fair you mentioned the defuns. I think what you are missing is that the goal is not to support arbitrarily complex snippets, handle every possible task or replicate yasnippet precisely only with sexp syntax. So we could as well say that field transformations are not an important feature. The same applies to #23 which does not seem that important.

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-17 13:16
> The example you gave is not a realistic example. It is a demonstration.

When I provided the org-id snippet as an example previously, you had said it was too complicated. So I tried to provide a simple example that was not designed to be realistic.

> So we could as well say that field transformations are not an important feature.

And it can be well said that #22 and #21 are clearly important features?

I do not think #4 is an important feature and will likely never use it myself, but I implemented it for the possibility of helping others.

Even if you do not add the feature having the form argument. It would make sense to have a <DEFAULT> for `s`.

> The same applies to #23 which does not seem that important.

There are two realistic examples for #23 (one which you provided). I would say the one I provided is not even realistic--it is real, because it is a snippet I actually created. And there are consistency reasons behind the change I recommended with `p`.

**Comment by minad** [comment] 2022-01-17 13:27
> When I provided the org-id snippet as an example previously, you had said it was too complicated. So I tried to provide a simple example that was not designed to be realistic.

Yes okay. Ideally, snippets we discuss are both realistic and simple. This allows us to judge better. But overall I think one should look into 

> And it can be well said that #22 and #21 are clearly important features?
> I do not think #4 is an important feature and will likely never use it myself, but I implemented it for the possibility of helping others.

#21 and #22 are features which are crucial in a sense that if they are missing you cannot implement certain snippets, snippets which depend on context and snippets which apply some post operation.

In comparison #23 are #25 seem more like accessibility details. For example I can very well live without field transformations (this issue #25), since as soon as the snippet expansion is done, the field transformation is also not active anymore. The value of field transformations is that not that high in my opinion.

The problem is that you try to port over some of your old fancy yasnippets, but it is not a goal here to replicate every yasnippet feature. So maybe some templates have to be written in a slightly different form or some details are not even possible, like field transformations. I wonder how many snippets with field transformations have you found overall in the snippet collections? I don't know a single one. Obviously I haven't looked far enough, but these features are not commonly used.

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-17 15:19
> are features which are crucial in a sense that if they are missing you cannot implement certain snippets, snippets which depend on context and snippets which apply some post operation.

You mean, you cannot implement them _from the file syntax_. So they are "crucial" if you insist on storing complex snippets in files.

The post operation I thought you mentioned could be done with elisp as well. `(ignore (org-edit-src-code))`.

However, something I did want to mention--I'm not sure if this is what you meant--is the concept of evaluating a field only when we jump to it. So maybe you want this "post-operation" to happen only when you get to that field. This could be interesting.

You can still implement them in elisp.

> The problem is that you try to port over some of your old fancy yasnippets

> or some details are not even possible, like field transformations.

What I want to emphasize is that the field transformations _already exist_ in `tempel`.

While this was inspired by a yasnippet snippet I created, I would not say I'm trying to port a yasnippet feature. I am trying to improve an _existing_ `tempel` feature.

Consider the following snippet (which you can copy and eval).

```elisp
(push `(lambda () (when (derived-mode-p 'text-mode)
		    '((doc (s docstring) "~~" (upcase (or docstring "")) "~~"))))
      tempel-template-sources)

;; => result of typing hello world
hello world~~HELLO WORLD~~
```

"hello world" is transformed into "HELLO WORLD". This is essentially a field transformation. 

The only problem is that the way things are, it cannot be done from the current field. A solution I recommended is to extend the `s` element--which should probably be extended (to be more similar to `p`) regardless.

**Comment by minad** [comment] 2022-01-17 16:50
For context, there are currently three essential yasnippet features we are missing here:

1. Post operations (#22)
2. Field transformations (this issue, #25)
3. Nested fields in default values

I consider 1. kind of important and would like to use it. The features 2. and 3. are less important according to my personal preferences. I have no important usage scenarios for those and they may not be worth the complications. Field transformations 2. are not hard to implement, but 3. is probably quite a pain since it would require significant changes to the current template expansion mechanism. Note that all features 1.-3. are orthogonal to existing features, all of them require new additions. At least 1. and 2. are not that difficult.

**Comment by Luis-Henriquez-Perez** [comment] 2022-01-17 18:14
> Not really. They are part of the trigger mechanism and it makes sense to have an easy and accessible method available to write down these trigger conditions.

I respect your opinion on this.

>  if your #4 is merged it will be very easy for users to install additional template files.

Still haven't received the assignment. :( I sent the email 9 days ago.

> But in fact, field transformations require a different implementation. I know this since I've tried.

O.K. I'll have to look more into this.

> I consider 1. kind of important and would like to use it.

 I don't think I understand very well what is meant by post-expansion. I'm thinking it's kind of like a hook run after `tempel-done`.

Other than editing source blocks, what would you like to use it for?

> Nested fields in default values

Sure sounds complicated.

**Comment by minad** [comment] 2022-01-17 18:17
> Still haven't received the assignment. :( I sent the email 9 days ago.

I am sure you will receive an answer this week. If not, write a friendly reminder mail.

> I don't think I understand very well what is meant by post-expansion. I'm thinking it's kind of like a hook run after tempel-done.
> Other than editing source blocks, what would you like to use it for?

I don't know. But source blocks are a simple and useful enough example to justify the addition I think.

>>  Nested fields in default values

> Sure sounds complicated.

Haha, I am glad that you agree. I expected that you made use of this feature in some of your snippets ;)

**Comment by minad** [comment] 2022-03-10 21:58
@Luis-Henriquez-Perez Not sure if there was agreement on this issue, but I consider field transformations of the current field out of scope of Tempel. Therefore I close the issue. We can reconsider if multiple (non-artificial) examples materialize which would make good use this functionality.

**Closed by minad** 2022-03-10 21:58 UTC
Labels: enhancement
