### ISSUE TITLE
Help on how to write snippets for verilog

### ISSUE THREAD

**Issue by C1oud555** [minad/tempel#100] opened 2023-04-21 12:01 UTC
I want to write some verilog snippets.
But when I want to insert new line. the `n` and the `n>` seems not working with leading spaces (within `verilog-mode`).

eg, a snippet to insert `begin` and `end`
```
(begin "begin" n> p n> "end")
```
with `n`
```
  begin

end
```
with `n>`
```
  begin

    end
```
I was wondering if there's approach to respect the leading spaces while insert snippets.
```
  begin

  end
```

I tried using the `:post (some-indent-command)` as a walk around, but that not work well in nested snippets.

**Comment by minad** [comment] 2023-04-21 12:46
It seems this question is a duplicate of #73 and #80. It is important to use the `>` templates elements at the right place. I cannot really tell you much more without trying it myself. `>` basically calls `indent-according-to-mode` and Tempel replays all the elements one by one. If you figure out a few useful snippets it would be great if you could tell me, then we can either add them to [tempel-collection](https://github.com/Crandel/tempel-collection) or to the Tempel README.

**Closed by minad** 2023-04-21 12:46 UTC

**Comment by C1oud555** [comment] 2023-04-21 14:28
I guess I kind of figure out how to indent the `begin ... end` pair after reading that two issue.
The `>` can be used separately to indent the thing I want to.
So add an `>' at the end of `(begin "begin" n> p n> "end")` will ok
```
(begin "begin" n> p n "end" >)
```
